export interface ReleaseNote {
  version: string
  date: string
  type: 'major' | 'minor' | 'patch'
  features: string[]
  fixes: string[]
  breaking: string[]
  summary: string
  ecosystem?: boolean
}

export interface RecentUpdate {
  title: string
  version: string
  description: string
  date: string
  type: 'feature' | 'fix' | 'breaking' | 'docs'
  icon: 'feature' | 'fix' | 'breaking' | 'docs'
}

// This will be auto-generated by our release script
export const RELEASE_NOTES: ReleaseNote[] = [
  {
  "version": "v1.1.1",
  "date": "2025-10-19",
  "type": "minor",
  "summary": "Ecosystem feature release with 1 new feature",
  "features": [
    "[EFD Admin] feat: implement automated release system with GitHub Actions"
  ],
  "fixes": [
    "[EFD Admin] fix(api): update wholesale API routes to use NextAuth v5 auth() function"
  ],
  "breaking": [],
  "ecosystem": true
},
  {
  "version": "v1.1.0",
  "date": "2025-10-19",
  "type": "minor",
  "summary": "Ecosystem feature release with 3 new features",
  "features": [
    "[EFD Admin] feat(admin): implement comprehensive wholesaler repair management system",
    "[EFD Admin] feat: complete wholesale management system with optimized logging",
    "[EFD Admin] feat(wholesale): implement wholesale application management system"
  ],
  "fixes": [
    "[EFD Admin] fix(auth): add missing providerMap export for signin page"
  ],
  "breaking": [],
  "ecosystem": true
},
  {
    version: 'v1.0.0',
    date: '2025-10-18',
    type: 'major',
    summary: 'Initial release of the Engel Fine Design documentation platform',
    features: [
      'Multi-select artisan types with dropdown+pills interface',
      'Unified ecosystem release management',
      'Role-based documentation access',
      'Modern documentation layout with table of contents',
      'Enhanced markdown rendering with visual callouts'
    ],
    fixes: [],
    breaking: []
  }
]

// Auto-generated from latest releases
export const RECENT_UPDATES: RecentUpdate[] = [
  {
    title: 'Documentation Platform Launch',
    version: 'v1.0.0',
    description: 'Complete documentation system with role-based access',
    date: '2025-10-18',
    type: 'feature',
    icon: 'feature'
  },
  {
    title: 'Multi-select Artisan Types',
    version: 'v1.0.0', 
    description: 'Added dropdown+pills interface for artisan type selection',
    date: '2025-10-18',
    type: 'feature',
    icon: 'feature'
  },
  {
    title: 'Ecosystem Release Management',
    version: 'v1.0.0',
    description: 'Unified versioning system across all applications',
    date: '2025-10-18',
    type: 'feature',
    icon: 'feature'
  }
]

// Get the latest N updates for dashboard
export const getRecentUpdates = (limit: number = 3): RecentUpdate[] => {
  return RECENT_UPDATES.slice(0, limit)
}

// Get release notes by version
export const getReleaseNotes = (version?: string): ReleaseNote | ReleaseNote[] => {
  if (version) {
    return RELEASE_NOTES.find(note => note.version === version) || RELEASE_NOTES[0]
  }
  return RELEASE_NOTES
}